Repository SocialiteProviders/Providers, pull requests merged in 2020-04, with the labels that each got.

#392 [Asana ] Fixed error in the mapUserToObject function
  src/Asana/Provider.php
Labels: bug

#374 Add keycloak provider
  monorepo-builder.yml
  src/Keycloak/KeycloakExtendSocialite.php
  src/Keycloak/Provider.php
  src/Keycloak/composer.json
Labels: new provider

#403 Fix Class does not comply with psr-4 autoloading standard
  monorepo-builder.yml
  src/AppNet/AppNetExtendSocialite.php
  src/AppNet/Provider.php
  src/AppNet/composer.json
  src/Azure/AzureExtendSocialite.php
  src/Azure/Provider.php
  src/Azure/composer.json
  src/Battlenet/BattlenetExtendSocialite.php
  src/Battlenet/Provider.php
  src/Battlenet/composer.json
  src/Bitly/BitlyExtendSocialite.php
  src/Bitly/Provider.php
  src/Bitly/composer.json
  src/Deviantart/DeviantartExtendSocialite.php
  src/Deviantart/Provider.php
  src/Deviantart/composer.json
  src/FiveHundredPixel/FiveHundredPixelExtendSocialite.php
  src/FiveHundredPixel/Provider.php
  src/FiveHundredPixel/Server.php
  src/FiveHundredPixel/composer.json
  src/Graph/GraphExtendSocialite.php
  src/Graph/Provider.php
  src/Graph/composer.json
  src/HumanApi/HumanApiExtendSocialite.php
  src/HumanApi/Provider.php
  src/HumanApi/composer.json
  src/Live/LiveExtendSocialite.php
  src/Live/Provider.php
  src/Live/composer.json
  src/Mattermost/MattermostExtendSocialite.php
  src/MediaCube/MediaCubeExtendSocialite.php
  src/MediaCube/Provider.php
  src/MediaCube/composer.json
  src/PayPalSandbox/PayPalSandboxExtendSocialite.php
  src/PayPalSandbox/Provider.php
  src/PayPalSandbox/composer.json
  src/TeamService/Provider.php
  src/TeamService/TeamServiceExtendSocialite.php
  src/TeamService/composer.json
  src/ThirtySevenSignals/Provider.php
  src/ThirtySevenSignals/ThirtySevenSignalsExtendSocialite.php
  src/ThirtySevenSignals/composer.json
  src/TwentyThreeAndMe/Provider.php
  src/TwentyThreeAndMe/TwentyThreeAndMeExtendSocialite.php
  src/TwentyThreeAndMe/composer.json
  src/WeixinWeb/Provider.php
  src/WeixinWeb/WeixinWebExtendSocialite.php
  src/WeixinWeb/composer.json
Labels: bug, enhancement
